# Generated by Django 5.0.6 on 2024-06-13 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_carts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carts',
        ),
    ]
