# Generated by Django 5.0.6 on 2024-07-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_orders_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address',
        ),
    ]
