# Generated by Django 5.0.6 on 2024-07-26 09:57

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(default=1, max_length=200, verbose_name=shop.models.ShippingAddress),
            preserve_default=False,
        ),
    ]
